<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.1" name="tileset" tilewidth="8" tileheight="8" tilecount="256" columns="16">
 <image source="../tileset.png" width="128" height="128"/>
 <tile id="0" type="solid"/>
 <tile id="1" type="solid"/>
 <tile id="2" type="solid"/>
 <tile id="3" type="solid"/>
 <tile id="4" type="solid"/>
 <tile id="5" type="solid"/>
 <tile id="6" type="solid"/>
 <tile id="7" type="solid"/>
 <tile id="8" type="solid"/>
 <tile id="9" type="solid"/>
 <tile id="10" type="solid"/>
 <tile id="11" type="solid"/>
 <tile id="12" type="solid"/>
 <tile id="16" type="solid"/>
 <tile id="17" type="solid"/>
 <tile id="18" type="solid"/>
 <tile id="19" type="solid"/>
 <tile id="20" type="solid"/>
 <tile id="21" type="solid"/>
 <tile id="22" type="solid"/>
 <tile id="23" type="solid"/>
 <tile id="24" type="solid"/>
 <tile id="25" type="solid"/>
 <tile id="26" type="solid"/>
 <tile id="27" type="solid"/>
 <tile id="28" type="solid"/>
 <tile id="32" type="solid"/>
 <tile id="33" type="solid"/>
 <tile id="34" type="solid"/>
 <tile id="35" type="solid"/>
 <tile id="36" type="solid"/>
 <tile id="37" type="solid"/>
 <tile id="38" type="solid"/>
 <tile id="39" type="solid"/>
 <tile id="40" type="solid"/>
 <tile id="41" type="solid"/>
 <tile id="48" type="solid"/>
 <tile id="49" type="solid"/>
 <tile id="50" type="solid"/>
 <tile id="51" type="solid"/>
 <tile id="52" type="solid"/>
 <tile id="53" type="solid"/>
 <tile id="54" type="solid"/>
 <tile id="55" type="solid"/>
 <tile id="56" type="solid"/>
 <tile id="57" type="solid"/>
</tileset>
