<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.4" tiledversion="1.4.3" name="tileset" tilewidth="8" tileheight="8" tilecount="256" columns="16">
 <image source="../tileset.png" width="128" height="128"/>
 <tile id="0" type="solid"/>
 <tile id="1" type="solid"/>
 <tile id="2" type="solid"/>
 <tile id="3" type="solid"/>
 <tile id="4" type="solid"/>
 <tile id="5" type="solid"/>
 <tile id="6" type="solid"/>
 <tile id="7" type="solid"/>
 <tile id="8" type="solid"/>
 <tile id="9" type="solid"/>
 <tile id="10" type="solid"/>
 <tile id="11" type="solid"/>
 <tile id="12" type="solid"/>
 <tile id="13" type="solid"/>
 <tile id="14" type="solid"/>
 <tile id="15" type="null"/>
 <tile id="16" type="solid"/>
 <tile id="17" type="solid"/>
 <tile id="18" type="solid"/>
 <tile id="19" type="solid"/>
 <tile id="20" type="solid"/>
 <tile id="21" type="solid"/>
 <tile id="22" type="solid"/>
 <tile id="23" type="solid"/>
 <tile id="24" type="solid"/>
 <tile id="25" type="solid"/>
 <tile id="26" type="solid"/>
 <tile id="27" type="solid"/>
 <tile id="28" type="solid"/>
 <tile id="29" type="solid"/>
 <tile id="30" type="solid"/>
 <tile id="31" type="null"/>
 <tile id="32" type="solid"/>
 <tile id="33" type="solid"/>
 <tile id="34" type="solid"/>
 <tile id="35" type="solid"/>
 <tile id="36" type="solid"/>
 <tile id="37" type="solid"/>
 <tile id="38" type="solid"/>
 <tile id="39" type="solid"/>
 <tile id="40" type="solid"/>
 <tile id="41" type="solid"/>
 <tile id="42" type="solid"/>
 <tile id="43" type="solid"/>
 <tile id="44" type="solid"/>
 <tile id="45" type="solid"/>
 <tile id="46" type="solid"/>
 <tile id="47" type="null"/>
 <tile id="48" type="solid"/>
 <tile id="49" type="solid"/>
 <tile id="50" type="solid"/>
 <tile id="51" type="solid"/>
 <tile id="52" type="solid"/>
 <tile id="53" type="solid"/>
 <tile id="54" type="solid"/>
 <tile id="55" type="solid"/>
 <tile id="56" type="solid"/>
 <tile id="57" type="solid"/>
 <tile id="58" type="solid"/>
 <tile id="59" type="solid"/>
 <tile id="60" type="solid"/>
 <tile id="61" type="solid"/>
 <tile id="62" type="solid"/>
 <tile id="63" type="null"/>
 <tile id="64" type="null"/>
 <tile id="65" type="null"/>
 <tile id="66" type="null"/>
 <tile id="67" type="null"/>
 <tile id="68" type="null"/>
 <tile id="69" type="null"/>
 <tile id="70" type="null"/>
 <tile id="71" type="null"/>
 <tile id="72" type="null"/>
 <tile id="73" type="null"/>
 <tile id="74" type="null"/>
 <tile id="75" type="solid"/>
 <tile id="76" type="solid"/>
 <tile id="77" type="solid"/>
 <tile id="78" type="solid"/>
 <tile id="79" type="null"/>
 <tile id="80" type="null"/>
 <tile id="81" type="null"/>
 <tile id="82" type="null"/>
 <tile id="83" type="null"/>
 <tile id="84" type="null"/>
 <tile id="85" type="null"/>
 <tile id="86" type="null"/>
 <tile id="87" type="null"/>
 <tile id="88" type="null"/>
 <tile id="89" type="null"/>
 <tile id="90" type="null"/>
 <tile id="91" type="solid"/>
 <tile id="92" type="solid"/>
 <tile id="93" type="solid"/>
 <tile id="94" type="solid"/>
 <tile id="95" type="null"/>
 <tile id="96" type="null"/>
 <tile id="97" type="null"/>
 <tile id="98" type="null"/>
 <tile id="99" type="null"/>
 <tile id="100" type="null"/>
 <tile id="101" type="null"/>
 <tile id="102" type="null"/>
 <tile id="103" type="null"/>
 <tile id="104" type="null"/>
 <tile id="105" type="null"/>
 <tile id="106" type="null"/>
 <tile id="107" type="null"/>
 <tile id="108" type="null"/>
 <tile id="109" type="null"/>
 <tile id="110" type="null"/>
 <tile id="111" type="null"/>
 <tile id="112" type="null"/>
 <tile id="113" type="null"/>
 <tile id="114" type="null"/>
 <tile id="115" type="null"/>
 <tile id="116" type="null"/>
 <tile id="117" type="null"/>
 <tile id="118" type="null"/>
 <tile id="119" type="null"/>
 <tile id="120" type="null"/>
 <tile id="121" type="null"/>
 <tile id="122" type="null"/>
 <tile id="123" type="null"/>
 <tile id="124" type="null"/>
 <tile id="125" type="null"/>
 <tile id="126" type="null"/>
 <tile id="127" type="null"/>
 <tile id="128" type="null"/>
 <tile id="129" type="null"/>
 <tile id="130" type="null"/>
 <tile id="131" type="null"/>
 <tile id="132" type="null"/>
 <tile id="133" type="null"/>
 <tile id="134" type="null"/>
 <tile id="135" type="null"/>
 <tile id="136" type="null"/>
 <tile id="137" type="null"/>
 <tile id="138" type="null"/>
 <tile id="139" type="null"/>
 <tile id="140" type="null"/>
 <tile id="141" type="null"/>
 <tile id="142" type="null"/>
 <tile id="143" type="null"/>
 <tile id="144" type="null"/>
 <tile id="145" type="null"/>
 <tile id="146" type="null"/>
 <tile id="147" type="null"/>
 <tile id="148" type="null"/>
 <tile id="149" type="null"/>
 <tile id="150" type="null"/>
 <tile id="151" type="null"/>
 <tile id="152" type="null"/>
 <tile id="153" type="null"/>
 <tile id="154" type="null"/>
 <tile id="155" type="null"/>
 <tile id="156" type="null"/>
 <tile id="157" type="null"/>
 <tile id="158" type="null"/>
 <tile id="159" type="null"/>
 <tile id="160" type="null"/>
 <tile id="161" type="null"/>
 <tile id="162" type="null"/>
 <tile id="163" type="null"/>
 <tile id="164" type="null"/>
 <tile id="165" type="null"/>
 <tile id="166" type="null"/>
 <tile id="167" type="null"/>
 <tile id="168" type="null"/>
 <tile id="169" type="null"/>
 <tile id="170" type="null"/>
 <tile id="171" type="null"/>
 <tile id="172" type="null"/>
 <tile id="173" type="null"/>
 <tile id="174" type="null"/>
 <tile id="175" type="null"/>
 <tile id="176" type="null"/>
 <tile id="177" type="null"/>
 <tile id="178" type="null"/>
 <tile id="179" type="null"/>
 <tile id="180" type="null"/>
 <tile id="181" type="null"/>
 <tile id="182" type="null"/>
 <tile id="183" type="null"/>
 <tile id="184" type="null"/>
 <tile id="185" type="null"/>
 <tile id="186" type="null"/>
 <tile id="187" type="null"/>
 <tile id="188" type="null"/>
 <tile id="189" type="null"/>
 <tile id="190" type="null"/>
 <tile id="191" type="null"/>
 <tile id="192" type="null"/>
 <tile id="193" type="null"/>
 <tile id="194" type="null"/>
 <tile id="195" type="null"/>
 <tile id="196" type="null"/>
 <tile id="197" type="null"/>
 <tile id="198" type="null"/>
 <tile id="199" type="null"/>
 <tile id="200" type="null"/>
 <tile id="201" type="null"/>
 <tile id="202" type="null"/>
 <tile id="203" type="null"/>
 <tile id="204" type="null"/>
 <tile id="205" type="null"/>
 <tile id="206" type="null"/>
 <tile id="207" type="null"/>
 <tile id="208" type="null"/>
 <tile id="209" type="null"/>
 <tile id="210" type="null"/>
 <tile id="211" type="null"/>
 <tile id="212" type="null"/>
 <tile id="213" type="null"/>
 <tile id="214" type="null"/>
 <tile id="215" type="null"/>
 <tile id="216" type="null"/>
 <tile id="217" type="null"/>
 <tile id="218" type="null"/>
 <tile id="219" type="null"/>
 <tile id="220" type="null"/>
 <tile id="221" type="null"/>
 <tile id="222" type="null"/>
 <tile id="223" type="null"/>
 <tile id="224" type="null"/>
 <tile id="225" type="null"/>
 <tile id="226" type="null"/>
 <tile id="227" type="null"/>
 <tile id="228" type="null"/>
 <tile id="229" type="null"/>
 <tile id="230" type="null"/>
 <tile id="231" type="null"/>
 <tile id="232" type="null"/>
 <tile id="233" type="null"/>
 <tile id="234" type="null"/>
 <tile id="235" type="null"/>
 <tile id="236" type="null"/>
 <tile id="237" type="null"/>
 <tile id="238" type="null"/>
 <tile id="239" type="null"/>
 <tile id="240" type="null"/>
 <tile id="241" type="null"/>
 <tile id="242" type="null"/>
 <tile id="243" type="null"/>
 <tile id="244" type="null"/>
 <tile id="245" type="null"/>
 <tile id="246" type="null"/>
 <tile id="247" type="null"/>
 <tile id="248" type="null"/>
 <tile id="249" type="null"/>
 <tile id="250" type="null"/>
 <tile id="251" type="null"/>
 <tile id="252" type="null"/>
 <tile id="253" type="null"/>
 <tile id="254" type="null"/>
 <tile id="255" type="null"/>
</tileset>
